version: "3"
services:
  backend:
    container_name: file-parser-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: file-parser/backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/file-parser
  frontend:
    container_name: file-parser-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    links:
      - "backend"
    image: file-parser/frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/file-parser